name: GitHub Pages Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme
          
      - name: Build documentation
        run: |
          mkdir -p docs_build/html
          cp README.md docs_build/html/index.md
          cp PROJECT_STRUCTURE.md docs_build/html/structure.md
          cp -r docs/* docs_build/html/
          
          # Create a simple HTML index page
          cat > docs_build/html/index.html << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Skin Cancer Classification Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            padding-top: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 2rem 0;
            margin-bottom: 2rem;
            border-bottom: 1px solid #e9ecef;
        }
        .project-title {
            color: #0d6efd;
        }
        .feature-icon {
            font-size: 1.5rem;
            margin-bottom: 1rem;
            color: #0d6efd;
        }
        .footer {
            margin-top: 3rem;
            padding: 2rem 0;
            background-color: #f8f9fa;
            border-top: 1px solid #e9ecef;
        }
        .card {
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            transition: transform 0.3s ease;
        }
        .card:hover {
            transform: translateY(-5px);
        }
        .btn-primary {
            background-color: #0d6efd;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header text-center">
            <h1 class="project-title">Professional Skin Cancer Classification Dashboard</h1>
            <p class="lead">A production-ready, AI-powered web application for skin cancer classification using state-of-the-art deep learning models</p>
            <div>
                <span class="badge bg-primary">Python 3.8+</span>
                <span class="badge bg-danger">Streamlit</span>
                <span class="badge bg-warning text-dark">PyTorch</span>
                <span class="badge bg-info text-dark">Deep Learning</span>
            </div>
        </div>

        <div class="row mb-5">
            <div class="col-md-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h3>Project Overview</h3>
                        <p>This dashboard uses advanced deep learning models to classify skin lesions into seven different categories, providing medical professionals with a valuable screening tool.</p>
                        <p>The project leverages EfficientNetV2-Medium architecture with custom classification heads and attention mechanisms to achieve high accuracy in lesion classification.</p>
                        <a href="structure.html" class="btn btn-primary">View Project Structure</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card h-100">
                    <div class="card-body">
                        <h3>Key Features</h3>
                        <ul>
                            <li><strong>Advanced AI Classification:</strong> Dual model support with UltraLight and EfficientNet variants</li>
                            <li><strong>Medical Intelligence:</strong> AI-powered diagnosis using Groq's DeepSeek R1</li>
                            <li><strong>Professional Reporting:</strong> PDF report generation with treatment recommendations</li>
                            <li><strong>Production Features:</strong> Comprehensive error handling and security</li>
                        </ul>
                        <a href="https://github.com/GauravPatil2515/skin-cancer-classification" class="btn btn-outline-primary">View on GitHub</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="feature-icon">🧠</h3>
                        <h4>Advanced Model</h4>
                        <p>Using EfficientNetV2-M architecture with custom classification head and attention mechanisms for high accuracy.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="feature-icon">📊</h3>
                        <h4>Visual Explanations</h4>
                        <p>GradCAM visualization provides explainable AI with heatmap overlays for better understanding.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="feature-icon">📄</h3>
                        <h4>PDF Reporting</h4>
                        <p>Generate comprehensive medical reports with professional formatting and treatment guidance.</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="text-center mt-5">
            <h3>Documentation</h3>
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5>Project Structure</h5>
                            <p>View the complete project structure and file organization</p>
                            <a href="structure.html" class="btn btn-sm btn-primary">View Structure</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5>Enhancement Summary</h5>
                            <p>Learn about all the enhancements implemented in the project</p>
                            <a href="ENHANCEMENT_SUMMARY.html" class="btn btn-sm btn-primary">View Enhancements</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5>GitHub Repository</h5>
                            <p>Access all source code and documentation on GitHub</p>
                            <a href="https://github.com/GauravPatil2515/skin-cancer-classification" class="btn btn-sm btn-primary">Visit GitHub</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="footer text-center">
            <p>© 2025 Gaurav Patil - Professional Skin Cancer Classification Dashboard</p>
            <p class="text-muted"><small>This tool is for research and educational purposes only. It is not intended for clinical diagnosis or treatment decisions.</small></p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
EOF
          
          # Convert Markdown files to HTML
          find docs_build/html -name "*.md" | while read md_file; do
            html_file="${md_file%.md}.html"
            echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Documentation</title><link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css'></head><body><div class='container my-5'>" > "$html_file"
            python -c "import markdown; print(markdown.markdown(open('$md_file', 'r').read()))" >> "$html_file"
            echo "</div></body></html>" >> "$html_file"
          done
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs_build/html
          clean: true
